/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Emil
 */
public class BuyPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyPanel
     */
    public BuyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        commentsOnTime = new javax.swing.JLabel();
        buyField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        barsLabel = new javax.swing.JLabel();
        itemField = new javax.swing.JTextField();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Last buy"));

        commentsOnTime.setText("testtkjsntkjsndflkjsdlfdslkfsdlkflkjdsfsdjlkdsjflkjsdfljksd");

        buyField.setEditable(false);
        buyField.setText("Vem blir först att köpa?");
        buyField.setFocusable(false);
        buyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buyField, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(commentsOnTime)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(buyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commentsOnTime)
                .addGap(27, 27, 27))
        );

        barsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bars.jpg"))); // NOI18N

        itemField.setEditable(false);
        itemField.setText("Vad ska du ha?");
        itemField.setFocusable(false);
        itemField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemField)
            .addComponent(barsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Scana produkt");
    }// </editor-fold>//GEN-END:initComponents

    private void itemFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFieldActionPerformed
        String barcode= ((JTextField) evt.getSource()).getText();
        
    }//GEN-LAST:event_itemFieldActionPerformed

    private void buyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barsLabel;
    private javax.swing.JTextField buyField;
    private javax.swing.JLabel commentsOnTime;
    private javax.swing.JTextField itemField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


    public void setUpItemInput(){
        
    }
    
    public void setItem(String name, String price){
        if(price.equals("")){
        	itemField.setText("Vad ska du ha?");
        }else {
        	itemField.setText("En " + name + " kostar " + price + " kr.");
        }
    	
        
//        itemLabel.setText(name);
//        priceLabel.setText(price);
    }
    
    public void setUser(String name, String item){
    	String format = "d/M G yyyy 'klockan' HH:mm";
    	SimpleDateFormat timeStamp = new SimpleDateFormat(format);
        
    	SimpleDateFormat weekDay = new SimpleDateFormat("E");
    	System.out.println(weekDay.format(new Date()));
    	if(weekDay.format(new Date()).equals("to")){
        	commentsOnTime.setText("På en TORSDAG???");
    	}
        buyField.setText(timeStamp.format(new Date()) + ": " + name +  " köpte en " + item);
    }
    
}
